import crypto from "crypto";

/**
 * ==========================================
 * PAYMENT REFERENCES & PROVIDER EVENT KEYS
 * ==========================================
 *
 * Two pure functions that decide the two identity strings the payment path depends on.
 * Both are here, next to each other, because they are the two places where a duplicate
 * would become a double charge or a double settlement.
 *
 * ── 1. `paymentReference` — the unique, non-financial reference we send the provider ─
 * Design §13.2: "`paymentReference` (unique; the value sent as `referenceId` — equals
 * `orderNumber` per the Phase 0 implementation, but stored explicitly so it can change
 * independently)".
 *
 * The schema makes it `@unique`, and that constraint is load-bearing rather than
 * decorative. Design §30.1's row 2 asks for exactly one *active* payment per order
 * ("`Payment.(orderId)` where `status IN (PENDING, UNPAID)`") and offers two mechanisms:
 * "a non-null `activePaymentKey` column ... or a transactional check + CAS". The shipped
 * Phase 2 schema has no `activePaymentKey`, and §30.3 is emphatic that a
 * check-then-create is a time-of-check/time-of-use race:
 *
 *   "two concurrent requests both read 'not exists' and both create. The design relies on
 *    the database rejecting the second write (`P2002` unique-violation), which is the only
 *    correct approach under concurrency."
 *
 * So the unique `paymentReference` IS the mechanism, and this function is how the two
 * kinds of reference are built:
 *
 *   attempt 1  →  `EVT-1758000000000-7f3a91c2`            (== `orderNumber`)
 *   attempt N  →  `EVT-1758000000000-7f3a91c2#2`          (distinct, still ours)
 *
 * Prefixing later attempts with the order number keeps the provider's `reference_id`
 * resolvable back to the order (the webhook resolves by `paymentReference`, so it does
 * not have to parse), and keeps the two order models from ever colliding: the retail
 * handler's own references begin `PAY-`, and design §35.7 names that prefix dispatch as
 * the cutover control that stops the two chains cross-settling.
 *
 * Design §13.2 allows at most ONE payment in a non-terminal state per order, which is
 * what makes sequential attempts legal while concurrent duplicates are impossible.
 */
export function buildPaymentReference(
    orderNumber: string,
    attemptNumber: number
): string {
    if (attemptNumber <= 1) {
        return orderNumber;
    }

    return `${orderNumber}#${attemptNumber}`;
}

/**
 * True when a reference belongs to the ticketing order namespace.
 *
 * Design §35.7: "Reference-prefix dispatch (`PAY-` vs `EVT-`) in the webhook — the two
 * order models cannot cross-settle." Ticketing order numbers are generated by
 * `lib/ticketing/checkout.ts` as `EVT-{epochMillis}-{8 hex}`, so the prefix is a
 * trustworthy namespace marker. Enforced as a second check after resolving the reference
 * to a `Payment` row, so that even a mis-registered reference cannot settle an EVT-
 * payment against the retail chain or vice versa.
 */
export function isTicketingReference(reference: string): boolean {
    return reference.startsWith("EVT-");
}

/**
 * The `Payment` a reference resolves to, parsed from a suffix-qualified reference.
 *
 * Attempt references are `${orderNumber}#${n}`, so the *order* number is the part before
 * the suffix. Used only to cross-check that a resolved payment's order matches the
 * reference we were handed; the authoritative lookup is always the unique
 * `Payment.paymentReference`.
 */
export function orderNumberFromReference(reference: string): string {
    const suffixIndex = reference.indexOf("#");

    return suffixIndex >= 0 ? reference.slice(0, suffixIndex) : reference;
}

/**
 * ── 2. `providerEventId` — the replay guard (design §31.2) ───────────────────────
 *
 * §31.2: "`providerEventId` | `String` | **`@unique`** — the replay guard. Derived from
 * the provider's transaction id (**and the event type if one transaction can produce
 * several event types**)".
 *
 * That parenthetical is exactly the case here: one iPaymu transaction can produce a
 * `payment.pending` and later a `payment.success` delivery. Using the transaction id
 * alone would make the success look like a duplicate of the pending and silently skip
 * settlement — a catastrophic bug. Including the event type keeps them distinct while
 * still collapsing a retry of the SAME event type into one row, which is what §31.4
 * requires ("Same event delivered 10 times → 1 × PROCESSED, 9 × IGNORED_DUPLICATE").
 *
 * §31.6 item 2 records the open question — "Whether the provider supplies a stable,
 * unique event/transaction id suitable as `providerEventId`" — and gives the fallback:
 * "Without it, the replay guard degrades to a payload hash (workable but weaker)."
 * `sha256(rawBody)` is that fallback. It is weaker in one specific way worth stating: two
 * *different* deliveries of an identical payload collapse into one row, which is exactly
 * the desired behavior for a retry, but it also means a provider that re-uses a payload
 * verbatim for a genuinely new event would be missed. Since the payload carries the
 * provider transaction id, verbatim identity implies the same transaction, so the
 * degradation is acceptable and is reported as a residual (not silently assumed away).
 *
 * The body hash is truncated to 32 hex characters only to keep the key readable in logs;
 * 128 bits of collision resistance is far beyond what this guard needs.
 */
export function buildProviderEventId(params: {
    provider: string;
    providerTransactionId: string | null;
    eventType: string;
    rawBody: string;
}): string {
    const transactionKey = params.providerTransactionId
        ? `trx-${params.providerTransactionId}`
        : `body-${sha256(params.rawBody).slice(0, 32)}`;

    return `${params.provider}:${transactionKey}:${params.eventType}`;
}

/**
 * SHA-256 of the raw body, as §31.2 requires:
 *
 *   "`payloadHash` | `String` | SHA-256 of the raw body. Two different payloads with the
 *    same `providerEventId` are a red flag and are stored with a note."
 *
 * Recorded on every row, including rejected ones, so a dispute can compare what the
 * provider says it sent against what we received.
 */
export function sha256(value: string): string {
    return crypto.createHash("sha256").update(value).digest("hex");
}
