/**
 * ==========================================
 * THE REALTIME INDICATOR — POSITION, LAYERING, UNIQUENESS
 * ==========================================
 *
 * The move to the bottom-right corner is a presentation change, and a presentation change is
 * exactly the kind that silently regresses: nothing throws, nothing fails to compile, and the only
 * witness is a human looking at a phone. So the properties the request actually asked for are
 * asserted here:
 *
 *   • it is FIXED (so it cannot consume layout space) and it sits on the RIGHT and BOTTOM edges;
 *   • it is NOT `sticky`/`relative`/`absolute`/`static`, which is what "does not affect layout"
 *     means in class terms;
 *   • the layer it occupies is BELOW every interactive overlay the project has (the sticky purchase
 *     bar, the dirty-form banner, Radix dialogs), so a status dot can never cover a close button;
 *   • on the phone breakpoints its inset clears the sticky purchase bar, at the SAME breakpoint the
 *     bar itself uses — so moving either one forces a look at the other;
 *   • there is EXACTLY ONE indicator in the application;
 *   • the labels, the live region and the accessible name survive, and colour is never the only
 *     signal;
 *   • the realtime plumbing behind it is untouched: the indicator imports nothing from the bus, the
 *     stream or the audience resolver, and the provider still wires the core, the `EventSource`, the
 *     channel and `router.refresh()`.
 *
 * Rendering uses `react-dom/server`, which is how the repository already asserts on markup (there is
 * no jsdom and no testing library here). `RealtimeIndicator` is a pure function of its props, so
 * this is a faithful render rather than an approximation of one.
 */

import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";

import { RealtimeIndicator } from "@/components/realtime/RealtimeIndicator";

const ROOT = join(__dirname, "..", "..");

const INDICATOR_SOURCE = readFileSync(
    join(ROOT, "components", "realtime", "RealtimeIndicator.tsx"),
    "utf8"
);
const PROVIDER_SOURCE = readFileSync(
    join(ROOT, "components", "realtime", "RealtimeProvider.tsx"),
    "utf8"
);

function html(options: { status: Parameters<typeof RealtimeIndicator>[0]["status"]; operator?: boolean }) {
    return renderToStaticMarkup(createElement(RealtimeIndicator, options));
}

/** The class attribute of the rendered pill, as a list of tokens. */
function classes(markup: string): string[] {
    const match = markup.match(/class="([^"]*)"/);

    return match ? match[1].split(/\s+/).filter(Boolean) : [];
}

/** Every .tsx file under app/ and components/. */
function surfaceFiles(): string[] {
    const files: string[] = [];

    const walk = (directory: string) => {
        for (const entry of readdirSync(directory)) {
            const full = join(directory, entry);

            if (statSync(full).isDirectory()) {
                walk(full);
                continue;
            }

            if (entry.endsWith(".tsx")) {
                files.push(full);
            }
        }
    };

    walk(join(ROOT, "app"));
    walk(join(ROOT, "components"));

    return files;
}

/* ==================================================================================
 * 1. POSITION
 * ================================================================================== */

describe("the indicator is pinned to the bottom-right and takes no layout space", () => {
    test("it is FIXED — that is what takes it out of flow", () => {
        const tokens = classes(html({ status: "live", operator: true }));

        expect(tokens).toContain("fixed");

        for (const flowPosition of ["static", "relative", "absolute", "sticky"]) {
            expect(tokens).not.toContain(flowPosition);
        }
    });

    test("it hugs the RIGHT and BOTTOM edges — and no longer the left", () => {
        const tokens = classes(html({ status: "live", operator: true }));

        expect(tokens).toContain("right-4");
        expect(tokens).toContain("lg:right-5");
        expect(tokens).toContain("lg:bottom-5");

        // The pill never anchors to the left edge at any breakpoint.
        expect(tokens.some((token) => /(^|:)left-(\d|\[)/.test(token))).toBe(false);

        /*
         * The BASE bottom offset must be the mobile expression, never a fixed step: a bare step
         * would drop the pill onto the purchase bar. And the only fixed-step bottom must be the
         * desktop one.
         *
         * Why this is expressed structurally instead of by listing the forbidden token names: the
         * stylesheet is generated by scanning every file in the project, `.ts` test files and their
         * COMMENTS included, and a utility is emitted for anything that looks like a class. Naming
         * the previous position's classes anywhere — even to forbid them — would ship them as dead
         * rules in the production CSS. Verified in the build output.
         */
        expect(tokens.filter((token) => /^bottom-\d+$/.test(token))).toEqual([]);
        expect(tokens.filter((token) => /^lg:bottom-\d+$/.test(token))).toEqual(["lg:bottom-5"]);
        expect(tokens.some((token) => token.startsWith("bottom-[calc("))).toBe(true);
    });

    test("desktop insets are 20px on both axes", () => {
        const tokens = classes(html({ status: "live" }));

        // Tailwind's numeric scale is 0.25rem per step: 5 → 1.25rem → 20px.
        expect(tokens).toContain("lg:right-5");
        expect(tokens).toContain("lg:bottom-5");
    });

    test("it cannot be interactive and cannot block a click", () => {
        const tokens = classes(html({ status: "live" }));

        expect(tokens).toContain("pointer-events-none");
    });

    test("it is a compact pill, not a toast or a card", () => {
        const tokens = classes(html({ status: "live" }));

        expect(tokens).toContain("rounded-full");
        expect(tokens).toContain("border");
        expect(tokens).toContain("shadow-sm");
        expect(tokens).toContain("backdrop-blur");
    });
});

/* ==================================================================================
 * 2. MOBILE — CLEAR THE PURCHASE BAR, AT THE SAME BREAKPOINT
 * ================================================================================== */

describe("the phone inset clears the sticky purchase bar", () => {
    test("below `lg` the pill sits ABOVE the bar, and on desktop it drops to 20px", () => {
        const tokens = classes(html({ status: "live" }));

        const mobileOffset = tokens.find((token) => token.startsWith("bottom-[calc("));

        expect(mobileOffset).toBe("bottom-[calc(4.5rem_+_env(safe-area-inset-bottom))]");

        // 4.5rem = 72px, which is taller than the bar (12px padding + ~40px of content) and so
        // leaves a visible gap rather than a touching edge.
        expect(mobileOffset).toContain("4.5rem");

        // Safe area handled the way the project already handles it.
        expect(mobileOffset).toContain("env(safe-area-inset-bottom)");

        // …and the desktop inset overrides it from the SAME breakpoint the bar hides at.
        expect(tokens).toContain("lg:bottom-5");
    });

    test("the breakpoints agree with the bar that forces the offset", () => {
        const bar = readFileSync(join(ROOT, "components", "ticketing", "StickyBuyBar.tsx"), "utf8");

        // The bar is the reason for the offset, so both must move together. If the bar ever stops
        // being `lg:hidden`, this test fails and the offset gets revisited.
        expect(bar).toContain("fixed inset-x-0 bottom-0");
        expect(bar).toContain("lg:hidden");

        expect(INDICATOR_SOURCE).toContain("lg:bottom-5");
        expect(INDICATOR_SOURCE).toContain("StickyBuyBar");
    });
});

/* ==================================================================================
 * 3. LAYERING
 * ================================================================================== */

describe("the pill floats above content but below everything interactive", () => {
    /**
     * Strip comments before looking for a z-index.
     *
     * Required, not cosmetic: these files EXPLAIN the ladder in their headers (the indicator's own
     * header names `z-50` to say why it does not use it), so scanning raw text would read a
     * rationale as a declaration.
     */
    const stripComments = (source: string): string =>
        source.replace(/\/\*[\s\S]*?\*\//g, "").replace(/^[ \t]*\/\/.*$/gm, "");

    const zOf = (source: string): number => {
        const found = [...stripComments(source).matchAll(/\bz-(\d+)/g)].map((match) => Number(match[1]));

        expect(found.length).toBeGreaterThan(0);

        return Math.max(...found);
    };

    test("z-index is the project's sticky-chrome rung, not an extreme value", () => {
        const tokens = classes(html({ status: "live" }));

        expect(tokens).toContain("z-30");

        // Nothing higher than the dialogs' rung, and no arbitrary value reaching for the top.
        expect(tokens.some((token) => /^z-\[/.test(token))).toBe(false);
        expect(tokens.some((token) => /^z-(4|5|9)\d$/.test(token))).toBe(false);
    });

    test("the interactive overlays all sit ABOVE it", () => {
        const indicator = zOf(INDICATOR_SOURCE);
        const banner = zOf(readFileSync(join(ROOT, "components", "realtime", "RealtimeRefreshBanner.tsx"), "utf8"));
        const stickyBar = zOf(readFileSync(join(ROOT, "components", "ticketing", "StickyBuyBar.tsx"), "utf8"));
        const dialog = zOf(readFileSync(join(ROOT, "components", "dashboard", "ui", "dialog.tsx"), "utf8"));

        // The dirty-form banner must win: it carries the two buttons the user has to be able to press.
        expect(indicator).toBeLessThan(banner);
        // The purchase bar must win: it carries the primary CTA.
        expect(indicator).toBeLessThan(stickyBar);
        // Modals and dropdowns must win: a status dot can never cover a close button.
        expect(indicator).toBeLessThan(dialog);
    });
});

/* ==================================================================================
 * 4. LABELS AND ACCESSIBILITY
 * ================================================================================== */

describe("the state semantics and the accessible name are preserved", () => {
    test("an operator sees Live / Menyambungkan… / Memperbarui… / Dijeda", () => {
        expect(html({ status: "live", operator: true })).toContain(">Live<");
        expect(html({ status: "connecting", operator: true })).toContain("Menyambungkan…");
        expect(html({ status: "fallback", operator: true })).toContain("Memperbarui…");
        expect(html({ status: "paused", operator: true })).toContain("Dijeda");
    });

    test("a CUSTOMER sees customer-friendly wording, never internal vocabulary", () => {
        const markup = html({ status: "live" });

        expect(markup).toContain(">Terhubung<");

        for (const internal of ["Stream", "stream", "SSE", "reconnect", "sync"]) {
            expect(markup).not.toContain(internal);
        }
    });

    test("a degraded connection stays VISIBLE rather than disappearing", () => {
        // Every status renders; nothing returns an empty string and hides itself.
        for (const status of ["connecting", "live", "fallback", "paused"] as const) {
            const markup = html({ status });

            expect(markup.length).toBeGreaterThan(0);
            expect(markup).toContain("fixed");
        }
    });

    test("it is a named, polite status region", () => {
        const markup = html({ status: "live", operator: true });

        expect(markup).toContain('role="status"');
        expect(markup).toContain('aria-live="polite"');
        expect(markup).toContain('aria-label="Status koneksi realtime: Live"');
    });

    test("the accessible name tracks the status", () => {
        expect(html({ status: "fallback", operator: true })).toContain(
            'aria-label="Status koneksi realtime: Memperbarui…"'
        );
        expect(html({ status: "paused", operator: true })).toContain(
            'aria-label="Status koneksi realtime: Dijeda"'
        );
        expect(html({ status: "connecting" })).toContain(
            'aria-label="Status koneksi realtime: Menyambungkan…"'
        );
    });

    test("colour is never the only signal", () => {
        // The dot is decorative and hidden from AT; the words carry the meaning.
        expect(html({ status: "live", operator: true })).toContain('aria-hidden="true"');

        expect(INDICATOR_SOURCE).toContain('<span>{label}</span>');
    });
});

/* ==================================================================================
 * 5. EXACTLY ONE
 * ================================================================================== */

describe("there is exactly one indicator in the application", () => {
    test("the provider renders it once", () => {
        const renders = PROVIDER_SOURCE.match(/<RealtimeIndicator\b/g) ?? [];

        expect(renders).toHaveLength(1);
    });

    test("no other file imports or renders it", () => {
        const others = surfaceFiles().filter(
            (file) =>
                !file.endsWith(join("realtime", "RealtimeIndicator.tsx")) &&
                !file.endsWith(join("realtime", "RealtimeProvider.tsx"))
        );

        const offenders = others.filter((file) => readFileSync(file, "utf8").includes("RealtimeIndicator"));

        expect(offenders).toEqual([]);
    });

    test("the single render is still fed live state, not a hard-coded status", () => {
        expect(PROVIDER_SOURCE).toMatch(/<RealtimeIndicator\s+status=\{status\}/);
    });
});

/* ==================================================================================
 * 6. THE REALTIME LOGIC BEHIND IT IS UNTOUCHED
 * ================================================================================== */

describe("only presentation moved", () => {
    test("the indicator imports nothing from the transport, the bus or the audience resolver", () => {
        const imports = [...INDICATOR_SOURCE.matchAll(/from "([^"]+)"/g)].map((match) => match[1]);

        expect(imports).toEqual(["@/lib/realtime/client-core"]);

        for (const forbidden of [
            "lib/realtime/bus",
            "lib/realtime/sse",
            "lib/realtime/audience",
            "lib/realtime/publishers",
        ]) {
            expect(INDICATOR_SOURCE).not.toContain(forbidden);
        }
    });

    test("the indicator performs no I/O and starts no timer", () => {
        for (const forbidden of [
            "EventSource",
            "BroadcastChannel",
            "setInterval",
            "setTimeout",
            "fetch(",
            "router.refresh",
            "useEffect",
        ]) {
            expect(INDICATOR_SOURCE).not.toContain(forbidden);
        }
    });

    test("no presentation leaked into the client core or the server transport", () => {
        for (const file of ["client-core.ts", "bus.ts", "sse.ts", "audience.ts", "taxonomy.ts"]) {
            const source = readFileSync(join(ROOT, "lib", "realtime", file), "utf8");

            for (const forbidden of ["className", "bottom-", "right-", "rounded-full", "z-30"]) {
                expect(source).not.toContain(forbidden);
            }
        }
    });

    test("the provider still owns the whole transport, unchanged", () => {
        for (const wiring of [
            "createRealtimeCore",
            "core.start()",
            "new EventSource(REALTIME_STREAM_PATH)",
            "new BroadcastChannel(REALTIME_CHANNEL_NAME)",
            "router.refresh()",
            "core.setVisible(",
            "core.setBlocked(",
            "isLeaderTab(",
            "parseRealtimeEnvelope(",
        ]) {
            expect(PROVIDER_SOURCE).toContain(wiring);
        }
    });
});
